[package]
name = "jogo_de_advinhacao_rust"
version = "0.1.0"
edition = "2021"
authors = ["Jonatas Oliveira <contact@jonatasoliveira.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"
